### ISSUE TITLE
Localized facet values - datetime, date, edtf & edtf intervals

### ISSUE THREAD

**Issue by mirekys** [oarepo/oarepo-model-builder#151]
- Create subclass of LabelledTermsFacet
- Pass the correct value_labels param to constructor of subclass
- Format facet date values inside the value_labels function

**Comment by mesemus** [comment]
https://github.com/oarepo/oarepo-runtime/pull/36

**Comment by mesemus** [comment]
Added facet classes & introduced in model builder
